# Generated by Django 4.2.7 on 2023-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('Adi', models.CharField(max_length=30)),
                ('Soyadi', models.CharField(max_length=20)),
            ],
        ),
    ]
