d = open("rehber.txt",encoding="utf-8")
# okunan = d.read()
okunan = d.read(5)
print(okunan)
# print(open("rehber.txt",encoding="utf-8").read())
okunan = d.read(5)
print(okunan)
okunan = d.read(5)
print(okunan)