print("\nKare alan çevre hesaplayıcı")
print("===========================\n")
abc = int( input ("Karenin kenar uzunluğu nedir? "))
print("Kenar uzunluğu",abc,"olan karenin çevresi",abc*4)
print("Kenar uzunluğu",abc,"olan karenin alanı  ",abc*abc)
input()
