# Join (dizi birleştirme)
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print("\nconcatenate :\n",arr3)

arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6], [7, 8]])
arr6 = np.concatenate((arr4, arr5))
arr7 = np.concatenate((arr4, arr5), axis=1)
print("\nconcatenate :\n",arr6)
print("\nconcatenate axis=1 :\n",arr7)

arr8 = np.array([1, 2, 3])
arr9 = np.array([4, 5, 6])
arr10 = np.stack((arr9, arr8), axis=1)
print("\nstack :\n",arr10)
arr11 = np.hstack((arr8, arr9))
print("\nhstack(horizontal) :\n",arr11)
arr12 = np.vstack((arr8, arr9))
print("\nvstack(vertical) :\n",arr12)
arr13 = np.dstack((arr8, arr9))
print("\ndstack(dimentional) :\n",arr13)

