print("\n\n\n               İSTİKLÂL MARŞI")
print("                         -Kahraman Ordumuza\n")
print("     Korkma, sönmez bu şafaklarda yüzen al sancak;")
print("     Sönmeden yurdumun üstünde tüten en son ocak.")
print("     O benim milletimin yıldızıdır, parlayacak;")
print("     O benimdir, o benim milletimindir ancak.\n")
print("     Çatma, kurban olayım çehreni ey nazlı hilâl!")
print("     Kahraman ırkıma bir gül… ne bu şiddet bu celâl?")
print("     Sana olmaz dökülen kanlarımız sonra helâl,")
print("     Hakkıdır, Hakk’a tapan, milletimin istiklâl.\n\n\n")
input()
