# Generated by Django 4.2.7 on 2023-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='Telefon',
            field=models.CharField(default=123, max_length=11),
            preserve_default=False,
        ),
    ]
