# Generated by Django 4.2.7 on 2023-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0003_alter_ogrenci_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.CharField(max_length=11)),
                ('AdiSoyadi', models.CharField(max_length=50)),
            ],
        ),
    ]
