print("╔═════════════════╗")
print("║    PARS ERP     ║")
print("╠═════════════════║")
print("║ 1-              ║")
print("║ 2-              ║")
print("║ 3-              ║")
print("║ 4-              ║")
print("║                 ║")
print("║                 ║")
print("║                 ║")
print("║                 ║")
print("╚═════════════════╝")
