print("\033[1;32;40m")
#print("╔"+"═"*20+"╗")
print("╔═════════════════════╗")
print("║\033[1;31;40m   ANA MENU  \033[1;32;40m        ║")
print("║                     ║")
print("║  1-Hesap makinesi   ║")
print("║  2-Oyunlar          ║")
print("║  3-Çizimler         ║")
print("║  4-                 ║")
print("║                     ║")
print("║Seçimiz nedir? (1/2/3)║")
print("╚═════════════════════╝")
# 201 ╔ # 205 ═ # 187 ╗ # 186 ║ # 200 ╚ # 188 ╝
secim = input()
if secim == "1" : print("Hesap makinesini seçtin")
if secim == "2" : print("Oyunları seçtin")
if secim == "3" : print("Çizimler")