def oyunmenu():
    print("╔═════════════════════╗")
    print("║  OYUNLAR            ║")
    print("║                     ║")
    print("║  1-Yılan            ║")
    print("║  2-Adam asmaca      ║")
    print("║  3-                 ║")
    print("║  4-                 ║")
    print("║                     ║")
    print("║    Seçimiz nedir?   ║")
    print("╚═════════════════════╝")
    s = input()
